apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
     matchLabels:
       app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
   name: jenkins-svc
spec:
   selector:
      app: jenkins
   ports:
      - name: jenkinsport
        targetPort: 8080
        port: 8080
        nodePort: 30000
      - name: jnlp-port
        targetPort: 50000
        port: 50000
        nodePort: 30001
   type: NodePort
